import { useState, type Dispatch, type SetStateAction } from 'react'
import { AudioControls } from './AudioGuide'
import { exhibits, films, formatTime, routes } from './content'
import { evidence, sourcePortals } from './evidence'
import { stopMinutes, type Journey } from './journey'
import { Action, type Panel } from './ui'
import { FilmArtwork, Icon, JourneyArtwork } from './Visuals'

export function VisitRoutePanel({ index, journey, start, resume, open }: { index: number; journey: Journey | null; start: (i: number) => void; resume: () => void; open: (p: Panel) => void }) {
  const [switching, setSwitching] = useState(false)
  const r = routes[index]
  const same = journey?.status === 'active' && journey.routeIndex === index
  return <><span className="archive-stamp">{r.tag} · 馆内参观计划</span><h2 className="panel-title">{r.title}</h2><p className="panel-description">{r.caption}</p><JourneyArtwork progress={{ step: same ? journey.step : -1, total: r.stops.length, finished: false }}/><div className="route-facts"><span><Icon name="clock" size={16}/>{r.minutes} 分钟</span><span><Icon name="pin" size={16}/>{r.stops.length} 个展厅</span><span><Icon name="audio" size={16}/>随身讲解</span></div><div className="timeline">{r.stops.map((s, n) => <button key={s} onClick={() => open({ kind: 'exhibit', index: s })}><i className={same && n < journey.step ? 'visited' : ''}>{same && n < journey.step ? <Icon name="check" size={13}/> : n + 1}</i><span className="row-text"><strong>{exhibits[s].name}</strong><small>建议 {stopMinutes(index, n)} 分钟 · {exhibits[s].tag}</small></span><Icon name="chevron" size={13}/></button>)}</div>{switching ? <div className="switch-route"><p>改走「{r.title}」将从第一站重新安排进度。已留下的足迹和收藏会保留。</p><Action onClick={() => start(index)}>确认更换路线</Action><Action secondary onClick={() => setSwitching(false)}>保留当前路线</Action></div> : <Action icon="compass" onClick={() => same ? resume() : journey?.status === 'active' ? setSwitching(true) : start(index)}>{same ? '继续这段旅程' : journey?.status === 'active' ? '改走这条路线' : '开始参观'}</Action>}<section className="route-alternatives"><h3>调整参观时间</h3><div className="list-group">{routes.map((option, i) => i !== index && <button key={option.title} className="list-row" onClick={() => open({ kind: 'route', index: i })}><span className="row-text"><strong>{option.title}</strong><small>{option.minutes} 分钟 · {option.stops.length} 个展厅</small></span><Icon name="chevron" size={14}/></button>)}</div></section><p className="context-note">时间包含步行与驻足，为参观建议。地图使用示意布局，请以现场导视为准。</p></>
}

export function ExhibitDetail({ index, favorite, toggleFavorite, open }: { index: number; favorite: boolean; toggleFavorite: () => void; open: (p: Panel) => void }) {
  const [layer, setLayer] = useState(0)
  const [object, setObject] = useState<number | null>(null)
  const item = exhibits[index], archive = evidence[index]
  return <><header className="archive-heading"><div><span className="archive-stamp">展厅索引 / {archive.archive}</span><h2>{item.name}</h2><p>{item.date} · {item.place}</p></div><button className={`circle-button ${favorite ? 'favorited' : ''}`} aria-label={favorite ? '取消收藏' : '收藏展项'} aria-pressed={favorite} onClick={toggleFavorite}><Icon name="heart"/></button></header><p className="spirit-caption"><span/>{item.spirit}</p><AudioControls index={index}/>
    <div className="segmented content-layers" aria-label="内容层次">{['30 秒看懂', '深入了解', '史料与出处'].map((label, i) => <button key={label} aria-pressed={layer === i} onClick={() => setLayer(i)}>{label}</button>)}</div>
    {layer === 0 && <article className="story-copy"><span className="archive-stamp">史实摘要</span><h3>{archive.question}</h3><p>{item.description}</p><button className="text-button" onClick={() => setLayer(1)}>阅读完整文字稿<Icon name="arrow" size={15}/></button></article>}
    {layer === 1 && <article className="story-copy transcript"><span className="archive-stamp">讲解文字稿 · 编辑解读</span><h3>{archive.question}</h3>{archive.paragraphs.map((paragraph, i) => <p key={i}><span className="paragraph-number">0{i + 1}</span>{paragraph}</p>)}<p className="context-note">本讲解为依据基础史实编写的参观解读，不是史料原文或场馆审定稿。</p></article>}
    {layer === 2 && <article className="source-layer"><h3>把故事，放回资料中。</h3><p>基础史实与参观解读分层呈现。下列链接为官方资料入口，便于进一步检索。</p><div className="source-fact"><span>基础史实</span><p>{item.description}</p></div>{sourcePortals.map(source => <a href={source.url} key={source.url} target="_blank" rel="noopener noreferrer"><Icon name="book" size={20}/><span><strong>{source.name}</strong><small>{source.description}</small></span><Icon name="arrow" size={16}/></a>)}<div className="source-fact"><span>资料核验状态</span><p>逐条原始文献、馆藏编号及学术观点尚未录入。这里不把机构首页标作原始资料，也不使用虚构馆藏号。</p></div><p className="context-note">展厅索引中的日期是内容编排标识，不是档案馆藏编号。展品名称为观看线索，实际陈列以现场为准。</p></article>}
    <div className="section-title"><h2>到展厅里看一看</h2></div><div className="object-chips">{archive.objects.map((name, i) => <button aria-pressed={object === i} key={name} onClick={() => setObject(object === i ? null : i)}><Icon name="book" size={16}/>{name}</button>)}</div>{object !== null && <div className="object-note"><strong>{archive.objects[object]}</strong><p>先读展签的年代、用途与来源，再看它和这一站的关系。请分清原件、复制品和复原陈列；实际展品以场馆为准。</p></div>}<Action secondary icon="explore" onClick={() => open({ kind: 'observation', index })}>带着一个问题去观察</Action><Action secondary icon="cinema" onClick={() => open({ kind: 'movie', index: index === 3 ? 1 : 0 })}>在空间放映中继续了解</Action></>
}

export function ObservationPanel({ index, complete, close, open }: { index: number; complete: (id: string) => void; close: () => void; open: (p: Panel) => void }) {
  const [observed, setObserved] = useState(false)
  const [answer, setAnswer] = useState<number | null>(null)
  const [done, setDone] = useState(false)
  const e = exhibits[index], task = evidence[index]
  if (done) return <div className="game-result"><span className="result-mark"><Icon name="check" size={40}/></span><span className="archive-stamp">观察印记 · {e.tag}</span><h2>你发现了一个线索。</h2><p>{task.explanation}</p><Action onClick={close}>收起手机，继续参观</Action></div>
  return <><span className="archive-stamp">观察任务 / 0{index + 1}</span><h2 className="panel-title">到{e.tag}，找一找。</h2><div className="observation-prompt"><Icon name="explore" size={35}/><h3>{task.observation}</h3><p>看一看「{task.objects[0]}」和旁边的说明。不急着回答，答案可能就在眼前。</p></div>{!observed ? <><Action onClick={() => setObserved(true)}>我已观察，记录发现</Action><Action secondary onClick={() => open({ kind: 'exhibit', index })}>现场没找到，先看资料</Action><p className="context-note">由你手动确认观察，不会自动验证到馆位置。</p></> : <><div className="answer-list">{task.options.map((option, i) => <button key={option} aria-pressed={answer === i} className={answer === i ? i === task.answer ? 'correct' : 'incorrect' : ''} onClick={() => setAnswer(i)}><span>{option}</span>{answer === i && <Icon name={i === task.answer ? 'check' : 'back'} size={17}/>}</button>)}</div>{answer !== null && <div className="answer-feedback" role="status">{answer === task.answer ? task.explanation : '再看看展签和时间标记，也可以回到文字资料寻找线索。'}</div>}<Action disabled={answer !== task.answer} onClick={() => { complete(`observe-${e.id}`); setDone(true) }}>保存这次观察</Action></>}</>
}

export type Projection = { filmIndex: number | null; playing: boolean; elapsed: number; volume: number; captions: boolean; queue: number[] }
export const emptyProjection: Projection = { filmIndex: null, playing: false, elapsed: 0, volume: 60, captions: true, queue: [] }
export function ProjectionPanel({ index, projection, setProjection, favorite, toggleFavorite }: { index: number; projection: Projection; setProjection: Dispatch<SetStateAction<Projection>>; favorite: boolean; toggleFavorite: () => void }) {
  const film = films[index]
  const active = projection.filmIndex === index
  const occupied = projection.filmIndex !== null && !active
  return <><div className="movie-preview"><FilmArtwork motif={film.motif}/><span className="preview-label">空间放映 · 控制演示</span><span className="projection-art-icon"><Icon name="cinema" size={42}/></span></div><div className="detail-title"><div><span className="eyebrow">{film.category} · 计划时长 {formatTime(film.duration)}</span><h2>{film.title}</h2></div><button className={`circle-button ${favorite ? 'favorited' : ''}`} aria-label={favorite ? '取消收藏影片' : '收藏影片'} onClick={toggleFavorite}><Icon name="heart"/></button></div><p className="panel-description">{film.description}</p><div className="room-status"><span><i className="status-dot"/>投影厅 A</span><strong>{active ? projection.playing ? '放映中' : projection.elapsed >= film.duration ? '已播放完毕' : '已暂停' : occupied ? '使用中' : '当前空闲'}</strong></div><p className="context-note">以下为本机模拟的空间控制；正式影片、真实占用情况与设备接口尚未接入。</p>
    {active ? <><div className="player-timeline"><input type="range" min={0} max={film.duration} value={projection.elapsed} aria-label="投影演示进度" onChange={e => setProjection(p => ({ ...p, elapsed: Number(e.target.value) }))}/><span>{formatTime(projection.elapsed)}<span>{formatTime(film.duration)}</span></span></div><Action icon={projection.playing ? 'pause' : 'play'} onClick={() => setProjection(p => ({ ...p, playing: !p.playing, elapsed: p.elapsed >= film.duration ? 0 : p.elapsed }))}>{projection.playing ? '暂停放映' : '继续放映'}</Action><div className="volume-control"><Icon name="volume" size={19}/><input type="range" aria-label="投影音量" min={0} max={100} value={projection.volume} onChange={e => setProjection(p => ({ ...p, volume: Number(e.target.value) }))}/><span>{projection.volume}%</span></div><button className="settings-line" role="switch" aria-checked={projection.captions} onClick={() => setProjection(p => ({ ...p, captions: !p.captions }))}><Icon name="caption"/><span>中文字幕</span><span className={`toggle ${projection.captions ? 'on' : ''}`}/></button>{projection.captions && <p className="projection-subtitle">{film.label}</p>}<Action secondary icon="close" onClick={() => setProjection(p => ({ ...p, filmIndex: p.queue[0] ?? null, queue: p.queue.slice(1), elapsed: 0, playing: p.queue.length > 0 }))}>{projection.queue.length ? '结束本片，播放队列下一部' : '结束投影，释放空间'}</Action></> : <Action icon="cinema" disabled={projection.queue.includes(index)} onClick={() => setProjection(p => occupied ? { ...p, queue: [...p.queue, index] } : { ...p, filmIndex: index, playing: true, elapsed: 0 })}>{projection.queue.includes(index) ? '已加入放映队列' : occupied ? '加入放映队列' : '投影播放 · 演示'}</Action>}
    {projection.queue.length > 0 && <div className="projection-queue"><h3>接下来放映</h3>{projection.queue.map((i, n) => <div key={i}><span>0{n + 1} · {films[i].title}</span><button aria-label={`移出队列${films[i].title}`} onClick={() => setProjection(p => ({ ...p, queue: p.queue.filter(v => v !== i) }))}><Icon name="close" size={16}/></button></div>)}</div>}</>
}
