import { useState } from 'react'
import { BrandMark, FilmArtwork, Icon, JourneyArtwork } from './Visuals'
import { exhibits, films, formatTime, routes, type IconName, type Tab } from './content'
import { Action, DeviceRow, PageHeader, SectionTitle, type Panel, type Saved } from './ui'

export function HomePage({ open, go, connected, connect }: { open: (p: Panel) => void; go: (t: Tab) => void; connected: boolean; connect: () => void }) {
  return <>
    <div className="home-top"><div className="wordmark"><BrandMark size={25}/><strong>栈川行</strong></div><button className="venue-button" onClick={() => go('guide')}><Icon name="pin" size={14}/>长征纪念馆<Icon name="chevron" size={11}/></button></div>
    <header className="home-heading"><div><p>很高兴，与你同行</p><h1>循着信仰，<br/>慢慢向前。</h1></div><button className="circle-button glass" aria-label="搜索" onClick={() => open({kind:'search'})}><Icon name="search" size={21}/></button></header>
    <section className="journey-card">
      <div className="journey-card-top"><span className="edition"><i/> 特别纪念 · 1936—2026</span><span className="anniversary">90<span>周年</span></span></div>
      <div className="journey-card-copy"><span className="eyebrow">THE LONG MARCH</span><h2>每一步，都有回响。</h2><p>跟随一条路线，走近一段历史。</p></div>
      <JourneyArtwork/>
      <div className="journey-card-bottom glass"><div><strong>信仰之路</strong><span>60 分钟 <i/> 5 个展厅</span></div><button aria-label="开启信仰之路" onClick={() => open({kind:'route',index:0})}><Icon name="arrow" size={22}/></button></div>
    </section>
    <div className="quick-actions" aria-label="快捷功能">{([{name:'compass',title:'场馆导览',action:()=>go('guide')},{name:'audio',title:'随身听讲',action:()=>open({kind:'exhibit',index:1})},{name:'cinema',title:'光影长征',action:()=>go('cinema')}] as {name:IconName;title:string;action:()=>void}[]).map(item=><button key={item.name} onClick={item.action}><Icon name={item.name} size={25}/><span>{item.title}</span></button>)}</div>
    <DeviceRow connected={connected} connect={connect}/>
    <SectionTitle title="此刻，值得驻足" more="全部" onClick={()=>go('guide')}/>
    <button className="editorial-row" onClick={()=>open({kind:'exhibit',index:1})}><span className="editorial-thumbnail"><span>遵义</span><small>1935</small></span><span className="row-text"><small>第二展厅 · 约 12 分钟</small><strong>一次转折，一种力量。</strong><span>从遵义会议，读懂独立自主。</span></span><Icon name="chevron" size={15}/></button>
    <p className="end-note">长征精神，始终在路上。</p>
  </>
}

export function GuidePage({ open }: { open: (p: Panel) => void }) {
  const [selected, setSelected] = useState(1)
  const [routeIndex, setRouteIndex] = useState(0)
  const [expanded, setExpanded] = useState(false)
  const positions = [[79,257],[115,91],[262,101],[273,245],[164,220]]
  return <><PageHeader label="FIND YOUR WAY" title="在历史中漫游" action={()=>open({kind:'search'})}/><div className="segmented" aria-label="路线选择">{routes.map((r,i)=><button key={r.title} aria-pressed={routeIndex===i} onClick={()=>setRouteIndex(i)}>{r.tag}</button>)}</div>
    <section className={`museum-map ${expanded ? 'expanded' : ''}`} aria-label="场馆示意地图"><div className="map-heading"><span>1F <i/> 常设展厅</span><button className="circle-button glass" aria-label={expanded?'缩小地图':'展开地图'} onClick={()=>setExpanded(!expanded)}><Icon name="expand" size={18}/></button></div>
      <svg viewBox="0 0 354 340" role="img" aria-label="可选择展厅的场馆示意图"><g className="map-rooms"><path d="M26 40h140v99H26zM188 40h141v99H188zM26 160h93v133H26zM141 160h68v80h-68zM231 160h98v133h-98zM141 261h68v32h-68z"/></g><path className="map-route-back" d="M79 257V162q0-17 17-17h19V91q0-18 18-18h110q19 0 19 19v9m0 15v29h11v100q0 19-19 19h-71q-19 0-19-19v-25"/><path className="map-route" d="M79 257V162q0-17 17-17h19V91"/>{exhibits.map((e,i)=><g key={e.id} className={`map-node ${selected===i?'selected':''}`} onClick={()=>setSelected(i)} tabIndex={0} role="button" aria-label={`查看${e.name}`} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();setSelected(i)}}}><circle cx={positions[i][0]} cy={positions[i][1]} r={selected===i?17:13}/><text x={positions[i][0]} y={positions[i][1]+4}>{(i+1).toString().padStart(2,'0')}</text></g>)}<g className="map-labels"><text x="46" y="65">遵义会议</text><text x="207" y="65">飞夺泸定桥</text><text x="38" y="183">征途启程</text><text x="244" y="183">雪山草地</text><text x="143" y="186">会师厅</text><text x="143" y="317">入口</text></g><g transform="translate(92 199)"><circle r="15" fill="white"/><circle r="6" fill="#b54046"/><circle r="22" fill="#b54046" opacity=".08"/></g></svg><span className="map-caption">场馆布局示意 · 点击节点查看</span>
    </section><div className="map-detail glass"><div className="map-detail-title"><span className="item-number">0{selected+1}</span><div><small>{exhibits[selected].tag}</small><h2>{exhibits[selected].name}</h2></div><span className="subtle-label">{exhibits[selected].minutes} 分钟</span></div><div className="two-actions"><Action secondary icon="audio" onClick={()=>open({kind:'exhibit',index:selected})}>听讲解</Action><Action icon="compass" onClick={()=>open({kind:'route',index:routeIndex})}>开始导览</Action></div></div>
    <SectionTitle title={routes[routeIndex].title}/><p className="section-description">{routes[routeIndex].caption}</p><div className="list-group">{routes[routeIndex].stops.map(i=><button className="list-row" key={i} onClick={()=>{setSelected(i);open({kind:'exhibit',index:i})}}><span className="list-number">0{i+1}</span><span className="row-text"><strong>{exhibits[i].name}</strong><small>{exhibits[i].tag} · {exhibits[i].minutes} 分钟</small></span><Icon name="chevron" size={14}/></button>)}</div></>
}

export function CinemaPage({ open, connected, connect }: { open: (p: Panel) => void; connected: boolean; connect: () => void }) {
  const [category, setCategory] = useState('全部')
  return <><PageHeader label="HISTORY IN MOTION" title="光影里的长征" action={()=>open({kind:'search'})}/><p className="page-description">找一个角落，让历史在眼前展开。</p><DeviceRow connected={connected} connect={connect}/><div className="text-tabs" aria-label="影片分类">{['全部','历史纪事','长征故事','人物叙事'].map(c=><button aria-pressed={category===c} onClick={()=>setCategory(c)} key={c}>{c}</button>)}</div>
    {films.map((film,i)=>(category==='全部'||category===film.category)&&<button className={`film-card ${i===0?'featured':''}`} key={film.id} onClick={()=>open({kind:'movie',index:i})}><div className="film-picture"><FilmArtwork motif={film.motif}/><span className="film-year">{film.year}<small>LONG MARCH</small></span><span className="film-duration glass"><Icon name="play" size={12}/>{formatTime(film.duration)}</span>{i===0&&<span className="film-editor">编辑精选</span>}</div><div className="film-description"><div><small>{film.category}</small><h2>{film.title}</h2><p>{film.label}</p></div><span className="round-arrow"><Icon name="arrow" size={20}/></span></div></button>)}<p className="end-note">影片为策划预览，正式影像待接入。</p></>
}

export function ExplorePage({ open, completed }: { open: (p: Panel)=>void; completed: string[] }) {
  return <><PageHeader label="LEARN BY EXPLORING" title="让好奇，带你向前" action={()=>open({kind:'settings'})} icon="settings"/><p className="page-description">在一次小小的探索中，与历史相遇。</p><button className="discovery-card" onClick={()=>open({kind:'game',index:0})}><div><span className="eyebrow">01 / 路线探索</span><h2>下一站，<br/>你来点亮。</h2><p>把散落的地点，连成一段征程。</p></div><JourneyArtwork compact/><div className="discovery-footer"><span>约 2 分钟 · 单人</span><span className="round-arrow"><Icon name="arrow" size={22}/></span></div></button><SectionTitle title="再多了解一点"/><button className="quiz-entry" onClick={()=>open({kind:'game',index:1})}><span className="outline-emblem"><Icon name="book" size={30}/></span><span className="row-text"><strong>长征五问</strong><small>5 个问题，读懂关键时刻</small></span><Icon name="chevron" size={16}/></button><SectionTitle title="探索印记"/><div className="imprint-row">{['路线探索','长征五问'].map((t,i)=><div className={completed.includes(i===0?'route':'quiz')?'earned':''} key={t}><span className="imprint-symbol"><Icon name={i===0?'route':'book'} size={26}/></span><strong>{t}</strong><small>{completed.includes(i===0?'route':'quiz')?'已完成':'等待点亮'}</small></div>)}</div><p className="quiet-quote">“走得再远，都不能忘记来时的路。”</p></>
}

export function ProfilePage({ open, saved }: { open: (p: Panel)=>void; saved: Saved }) {
  return <><PageHeader label="YOUR OWN JOURNEY" title="每一步，都算数" action={()=>open({kind:'settings'})} icon="settings"/><div className="profile-person"><span className="profile-monogram"><BrandMark size={40}/></span><div><h2>同行的你</h2><p>很高兴，与你分享这段历史。</p></div></div><div className="profile-stats"><div><strong>{saved.visited.length}<small> / 5</small></strong><span>听过的故事</span></div><div><strong>{saved.completed.length}<small> / 2</small></strong><span>探索印记</span></div><div><strong>{saved.favorites.length}</strong><span>珍藏内容</span></div></div><section className="footprint-card"><span className="eyebrow">MY LONG MARCH</span><h2>属于你的征途</h2><JourneyArtwork compact/><div className="footprint-stops">{exhibits.map((e,i)=><button aria-label={`查看${e.name}`} className={saved.visited.includes(e.id)?'done':''} key={e.id} onClick={()=>open({kind:'exhibit',index:i})}><i>{saved.visited.includes(e.id)?<Icon name="check" size={12}/>:i+1}</i><span>{['出发','遵义','泸定','雪山','会师'][i]}</span></button>)}</div></section><div className="list-group profile-links"><button className="list-row" onClick={()=>open({kind:'collection'})}><Icon name="heart"/><span className="row-text"><strong>我的收藏</strong></span><span className="muted">{saved.favorites.length}</span><Icon name="chevron" size={14}/></button><button className="list-row" onClick={()=>open({kind:'card'})}><Icon name="download"/><span className="row-text"><strong>旅程纪念卡</strong></span><Icon name="chevron" size={14}/></button><button className="list-row" onClick={()=>open({kind:'settings'})}><Icon name="settings"/><span className="row-text"><strong>阅读与显示</strong></span><Icon name="chevron" size={14}/></button></div><p className="end-note">足迹保存在当前设备，无需登录。</p></>
}
