import { useState } from 'react'
import { BrandMark, FilmArtwork, Icon, JourneyArtwork } from './Visuals'
import { exhibits, films, formatTime, routes, type Tab } from './content'
import { Action, PageHeader, SectionTitle, type Panel, type Saved } from './ui'
import { stopMinutes, walkingInfo, type Journey } from './journey'
import { useAudioGuide } from './AudioGuide'
import { MuseumMap } from './MuseumMap'
import { projectionLabels, type Projection } from './projection'

type RobotProps = { connected: boolean; connect: () => void; lead: () => void; guiding: boolean }
export function CompanionCard({ connected, connect, lead, guiding }: RobotProps) {
  return <section className="companion-card"><div className="companion-head"><span className="small-icon"><Icon name="robot" size={22}/></span><div><h3>同行机器人</h3><p>{connected ? '机器人 A07 · 演示连接' : '让向导陪你走一程'}</p></div><button className="text-button" onClick={connect}>{connected ? '管理' : '连接'}<Icon name="chevron" size={12}/></button></div>{connected && <><div className="robot-telemetry"><span><i className="status-dot"/>{guiding ? '带路任务进行中' : '已连接'}</span><span><Icon name="battery" size={16}/>82%</span><span>距你 3.2 米</span></div><button className="robot-lead" onClick={lead}>{guiding ? '查看带路路线' : '让它带路'}<Icon name="arrow" size={18}/></button><p className="data-note">电量、距离与任务为演示数据</p></>}</section>
}

type VisitProps = { journey: Journey | null; start: (index: number) => void }
export function GuidePage({ open, journey, start, arrive, advance, ...robot }: { open: (p: Panel) => void; arrive: () => void; advance: () => void } & VisitProps & RobotProps) {
  const [choice, setChoice] = useState(0)
  const [selected, setSelected] = useState<number | null>(null)
  const [expanded, setExpanded] = useState(false)
  const active = journey?.status === 'active'
  const routeIndex = active ? journey.routeIndex : choice
  const route = routes[routeIndex]
  const target = active ? route.stops[journey.step] : route.stops[0]
  const from = active ? journey.arrived ? target : journey.flags.at(-1) ?? null : null
  const walking = walkingInfo(from, target)
  const a = useAudioGuide()
  return <><PageHeader label="馆内导览" title={active ? '下一站，清楚一点。' : '找到你的参观路线'} action={() => open({ kind: 'search' })}/><div className="map-context"><span><Icon name="pin" size={14}/>手动确认位置</span><small>布局与距离为示意</small></div>
    {!active && <div className="segmented" aria-label="路线选择">{routes.map((r, i) => <button key={r.title} aria-pressed={routeIndex === i} onClick={() => setChoice(i)}>{r.minutes} 分钟 · {r.tag.slice(0, 2)}</button>)}</div>}
    <section className={`museum-map action-map ${expanded ? 'expanded' : ''}`} aria-label="行动导览地图"><div className="map-heading"><span>1F <i/> 常设展厅</span><button className="circle-button glass" aria-label={expanded ? '缩小地图' : '展开地图'} onClick={() => setExpanded(!expanded)}><Icon name="expand" size={18}/></button></div><MuseumMap from={from} target={target} selected={selected} flags={journey?.flags ?? []} stops={route.stops} onSelect={setSelected}/><div className="map-legend"><span><i/>目标站</span><span><Icon name="flag" size={12}/>已到达</span><button onClick={() => setSelected(null)}>回到路线<Icon name="pin" size={12}/></button></div></section>
    <section className="navigation-card glass"><div className="navigation-card-top"><span>{active && journey.arrived ? '你已到达' : '接下来去'}</span><span>{active ? `${journey.step + 1} / ${route.stops.length}` : `${route.minutes} 分钟路线`}</span></div><h2>{exhibits[target].name}</h2><p>{active && journey.arrived ? `${exhibits[target].tag} · 建议停留约 ${stopMinutes(routeIndex, journey.step)} 分钟` : `示意距离 ${walking.meters} 米 · 步行约 ${walking.minutes} 分钟`}</p>
      {active ? journey.arrived ? <><Action icon="audio" onClick={() => { a.play(target); open({ kind: 'exhibit', index: target }) }}>听这一站的讲解</Action><Action secondary onClick={advance}>{journey.step === route.stops.length - 1 ? '完成本次参观' : '这一站看完了，去下一站'}</Action></> : <><p className="wayfinding-copy">从{from === null ? '入口' : exhibits[from].name}沿连廊前往{exhibits[target].tag}。请以现场导视为准。</p><Action icon="check" onClick={arrive}>我已到达{exhibits[target].name}</Action></> : <Action icon="compass" onClick={() => start(routeIndex)}>开始这条路线</Action>}
    </section>
    {selected !== null && <div className="selected-exhibit"><span>查看展厅</span><h3>{exhibits[selected].name}</h3><p>{exhibits[selected].tag} · {exhibits[selected].spirit}</p><button onClick={() => open({ kind: 'exhibit', index: selected })}>展厅详情与讲解<Icon name="arrow" size={17}/></button></div>}
    {active && journey.routeIndex === 1 && <button className="switch-shortcut" onClick={() => open({ kind: 'route', index: 0 })}><Icon name="clock" size={17}/><span>时间不够，切换到重点线路<small>已插下的旗标会保留</small></span><Icon name="arrow" size={16}/></button>}{robot.connected && <CompanionCard {...robot}/>}<SectionTitle title={route.title} more="路线详情" onClick={() => open({ kind: 'route', index: routeIndex })}/><div className="list-group">{route.stops.map((i, n) => <button className="list-row" key={i} onClick={() => open({ kind: 'exhibit', index: i })}><span className={`list-number ${journey?.flags.includes(i) ? 'stop-done' : ''}`}>{journey?.flags.includes(i) ? <Icon name="flag" size={14}/> : `0${n + 1}`}</span><span className="row-text"><strong>{exhibits[i].name}</strong><small>{exhibits[i].tag} · 建议 {stopMinutes(routeIndex, n)} 分钟</small></span>{active && n === journey.step ? <span className="current-tag">当前站</span> : <Icon name="chevron" size={14}/>}</button>)}</div></>
}

export function CinemaPage({ open, projection }: { open: (p: Panel) => void; projection: Projection }) {
  const [category, setCategory] = useState('全部')
  return <><PageHeader label="空间里的故事" title="沉浸放映" action={() => open({ kind: 'search' })}/><p className="page-description">手机是控制器，空间才是屏幕。</p>{projection.filmIndex !== null ? <button className="cinema-session" onClick={() => open({kind:'movie',index:projection.filmIndex!})}><span className="companion-glyph"><Icon name="robot" size={25}/></span><span><strong>{films[projection.filmIndex].title}</strong><small>{projectionLabels[projection.stage]} · 演示</small></span><Icon name="arrow" size={18}/></button> : <div className="cinema-intro"><Icon name="robot" size={20}/><span>选好内容，一键召唤。<small>到固定投影点后确认开始 · 演示</small></span></div>}<div className="text-tabs" aria-label="影片分类">{['全部', '历史纪事', '长征故事', '人物叙事', '趣味游戏'].map(c => <button aria-pressed={category === c} onClick={() => setCategory(c)} key={c}>{c}</button>)}</div>
    {films.map((film, i) => (category === '全部' || category === film.category) && <button className={`film-card ${i === 1 ? 'featured' : ''}`} key={film.id} onClick={() => open({ kind: 'movie', index: i })}><div className="film-picture"><FilmArtwork motif={film.motif}/><span className="film-year">{film.year}<small>{film.game ? '五关仿真冒险' : '长征影像计划'}</small></span><span className="film-duration glass"><Icon name="play" size={12}/>{film.game ? '五关互动' : formatTime(film.duration)}</span></div><div className="film-description"><div><small>{film.category} · {film.game ? '仿真游戏' : '策划内容'}</small><h2>{film.title}</h2><p>{film.label}</p></div><span className="round-arrow"><Icon name="arrow" size={20}/></span></div></button>)}<p className="end-note">当前体验放映控制流程，授权影片与真实设备待接入。</p></>
}

export function ExplorePage({ open, completed, journey }: { open: (p: Panel) => void; completed: string[]; journey: Journey | null }) {
  const current = journey?.status === 'active' ? routes[journey.routeIndex].stops[journey.step] : 0
  return <><PageHeader label="一起参与这段征途" title="把历史，走成故事" action={() => open({ kind: 'settings' })} icon="settings"/><p className="page-description">在投影里协作，在展厅里发现。</p>
    <button className="interactive-hero" onClick={() => open({ kind: 'movie', index: 3 })}><span className="archive-stamp">空间互动 · 五关冒险</span><Icon name="flag" size={40}/><h2>红星小队，出发！</h2><p>整装集合、点亮时间线、桥面寻路、草地绕行、会师接力。</p><span className="interactive-cta">召唤机器人，一起闯关<Icon name="arrow" size={21}/></span></button>
    <p className="context-note">仿真投影游戏，可点击地面或用方向键移动。实际体感识别需接入设备。</p>
    <SectionTitle title="就在眼前的小发现"/><button className="list-row observation-shortcut" onClick={() => open({ kind: 'observation', index: current })}><span className="small-icon"><Icon name="explore"/></span><span className="row-text"><strong>{exhibits[current].name} · 找一个线索</strong><small>{completed.includes(`observe-${exhibits[current].id}`) ? '本次观察已完成，可再次查看' : '先看展览，再记录发现 · 约 2 分钟'}</small></span><Icon name="chevron" size={16}/></button>
    <SectionTitle title="参观后的小回顾"/><div className="list-group"><button className="list-row" onClick={() => open({ kind: 'game', index: 0 })}><Icon name="route"/><span className="row-text"><strong>把七站连成一程</strong><small>按历史顺序点亮路线</small></span><Icon name="chevron" size={14}/></button><button className="list-row" onClick={() => open({ kind: 'game', index: 1 })}><Icon name="book"/><span className="row-text"><strong>长征五问</strong><small>和同行的人一起想一想</small></span><Icon name="chevron" size={14}/></button></div><p className="end-note">更多观察任务，在每个展厅详情里。</p></>
}

export function ProfilePage({ open, saved, journey }: { open: (p: Panel) => void; saved: Saved; journey: Journey | null }) {
  return <><PageHeader label="我的参观足迹" title="每一步，都算数" action={() => open({ kind: 'settings' })} icon="settings"/><div className="profile-person"><span className="profile-monogram"><BrandMark size={40}/></span><div><h2>同行的你</h2><p>陪你走完一段历史。</p></div></div><div className="profile-stats"><div><strong>{journey?.flags.length ?? 0}<small> / 7</small></strong><span>到达旗标</span></div><div><strong>{saved.completed.filter(c => c.startsWith('observe-')).length}<small> / 7</small></strong><span>观察印记</span></div><div><strong>{saved.favorites.length}</strong><span>珍藏内容</span></div></div><section className="footprint-card"><span className="eyebrow">{journey ? routes[journey.routeIndex].title : '属于你的征途'}</span><h2>{journey?.status === 'finished' ? '这一程，已完成。' : '循着信仰，慢慢向前。'}</h2><JourneyArtwork progress={{ step: journey?.step ?? -1, total: journey ? routes[journey.routeIndex].stops.length : 7, finished: journey?.status === 'finished', marked: journey ? routes[journey.routeIndex].stops.flatMap((stop, i) => journey.flags.includes(stop) ? [i] : []) : [] }}/><div className="footprint-stops">{exhibits.map((e, i) => <button aria-label={`查看${e.name}`} className={journey?.flags.includes(i) ? 'done' : ''} key={e.id} onClick={() => open({ kind: 'exhibit', index: i })}><i>{journey?.flags.includes(i) ? <Icon name="flag" size={12}/> : i + 1}</i><span>{e.name}</span></button>)}</div></section><div className="list-group profile-links"><button className="list-row" onClick={() => open({ kind: 'collection' })}><Icon name="heart"/><span className="row-text"><strong>我的收藏</strong></span><span className="muted">{saved.favorites.length}</span><Icon name="chevron" size={14}/></button><button className="list-row" onClick={() => open({ kind: 'card' })}><Icon name="download"/><span className="row-text"><strong>旅程纪念卡</strong></span><Icon name="chevron" size={14}/></button><button className="list-row" onClick={() => open({ kind: 'settings' })}><Icon name="settings"/><span className="row-text"><strong>阅读与显示</strong></span><Icon name="chevron" size={14}/></button></div><p className="end-note">足迹保存在当前设备，无需登录。</p></>
}
