import { useState } from 'react'
import { BrandMark, FilmArtwork, Icon, JourneyArtwork } from './Visuals'
import { exhibits, films, formatTime, routes, type Tab } from './content'
import { Action, PageHeader, SectionTitle, type Panel, type Saved } from './ui'
import { mapPoints, remainingMinutes, stopMinutes, walkingInfo, walkingPath, type Journey } from './journey'
import { useAudioGuide } from './AudioGuide'
import { evidence } from './evidence'
import type { Projection } from './ExperiencePanels'

type RobotProps = { connected: boolean; connect: () => void; lead: () => void; guiding: boolean }
export function CompanionCard({ connected, connect, lead, guiding }: RobotProps) {
  return <section className="companion-card"><div className="companion-head"><span className="small-icon"><Icon name="robot" size={22}/></span><div><h3>同行机器人</h3><p>{connected ? '机器人 A07 · 演示连接' : '让向导陪你走一程'}</p></div><button className="text-button" onClick={connect}>{connected ? '管理' : '连接'}<Icon name="chevron" size={12}/></button></div>{connected && <><div className="robot-telemetry"><span><i className="status-dot"/>{guiding ? '带路任务进行中' : '已连接'}</span><span><Icon name="battery" size={16}/>82%</span><span>距你 3.2 米</span></div><button className="robot-lead" onClick={lead}>{guiding ? '查看带路路线' : '让它带路'}<Icon name="arrow" size={18}/></button><p className="data-note">电量、距离与任务为演示数据</p></>}</section>
}

type VisitProps = { journey: Journey | null; start: (index: number) => void }
export function HomePage({ open, go, journey, start, resume, ...robot }: { open: (p: Panel) => void; go: (t: Tab) => void; resume: () => void } & VisitProps & RobotProps) {
  const [choice, setChoice] = useState(0)
  const a = useAudioGuide()
  const route = routes[journey?.routeIndex ?? choice]
  const current = journey ? route.stops[journey.step] : route.stops[0]
  const next = journey && journey.step < route.stops.length - 1 ? route.stops[journey.step + 1] : null
  const active = journey?.status === 'active'
  const from = journey && journey.step > 0 ? route.stops[journey.step - 1] : null
  const walk = walkingInfo(from, current)
  return <>
    <div className="home-top"><div className="wordmark"><BrandMark size={25}/><strong>栈川行</strong></div><button className="circle-button glass" aria-label="搜索" onClick={() => open({ kind: 'search' })}><Icon name="search" size={20}/></button></div>
    <header className="visit-heading"><p><Icon name="pin" size={13}/>长征纪念馆<span>参观演示</span></p><h1>今日参观</h1><span>{active ? '下一步，就在这里。' : '留一点时间，走近一段历史。'}</span></header>
    <section className={`visit-card ${active ? 'is-active' : ''}`} aria-label="当前旅程">
      <div className="visit-card-top"><span><i className="status-dot"/>{active ? '正在参观' : journey ? '旅程已完成' : '为你安排一段旅程'}</span><span>{active ? route.tag : '1936 — 2026'}</span></div>
      {journey ? <><div className="visit-title"><h2>{route.title}</h2>{active && <button onClick={() => open({ kind: 'route', index: journey.routeIndex })}>路线详情<Icon name="chevron" size={12}/></button>}</div><div className="visit-current"><span className="visit-count">{String(journey.status === 'finished' ? route.stops.length : journey.step + 1).padStart(2, '0')}<small> / {String(route.stops.length).padStart(2, '0')}</small></span><div><h3>{active ? exhibits[current].name : '每一步，都有回响。'}</h3><p>{active ? journey.arrived ? '已到达 · 可以开始听讲解' : `前往${exhibits[current].tag} · 示意步行约 ${walk.minutes} 分钟` : '这一段历史，已留在你的足迹里。'}</p></div></div><JourneyArtwork progress={{ step: journey.step, total: route.stops.length, finished: !active }}/><div className="visit-estimate"><span><Icon name="clock" size={14}/>{active ? `预计剩余约 ${remainingMinutes(journey)} 分钟` : '本次参观已完成'}</span><small>{active ? '按路线安排估算' : '记录保存在本机'}</small></div><Action onClick={active ? resume : () => go('profile')}>{active ? '继续导览' : '查看本次足迹'}</Action>{!active && <button className="new-journey" onClick={() => open({ kind: 'route', index: 0 })}>再开启一段旅程</button>}</> : <><h2 className="time-question">你有多少时间？</h2><div className="time-options" aria-label="参观时长">{[1, 2, 0].map(i => <button aria-pressed={choice === i} key={i} onClick={() => setChoice(i)}><strong>{routes[i].minutes}</strong><span>分钟</span></button>)}</div><div className="chosen-route"><div><h3>{route.title}</h3><p>{route.stops.length} 个展厅 · {route.tag}</p></div><Icon name="route" size={24}/></div><JourneyArtwork progress={{ step: -1, total: route.stops.length, finished: false }}/><Action onClick={() => start(choice)}>开始参观</Action><p className="visit-hint">可以随时暂停，回来继续。</p></>}
    </section>
    <SectionTitle title="现在可以做"/><div className="quick-actions v3-quick" aria-label="参观快捷功能"><button onClick={() => { a.play(current); open({ kind: 'exhibit', index: current }) }}><Icon name="audio" size={24}/><span>听讲解</span></button><button onClick={() => go('guide')}><Icon name="compass" size={24}/><span>看地图</span></button><button onClick={robot.connect}><Icon name="robot" size={24}/><span>{robot.connected ? '我的机器人' : '连接机器人'}</span></button></div>
    {active && next !== null && <button className="next-stop-row" onClick={() => open({ kind: 'exhibit', index: next })}><span className="next-index">{String(journey!.step + 2).padStart(2, '0')}</span><span className="row-text"><small>下一站</small><strong>{exhibits[next].name}</strong></span><span>约 {stopMinutes(journey!.routeIndex, journey!.step + 1)} 分钟</span><Icon name="chevron" size={14}/></button>}
    <CompanionCard {...robot}/><SectionTitle title="此刻，值得驻足" more="全部展厅" onClick={() => go('guide')}/><button className="archive-feature" onClick={() => open({ kind: 'exhibit', index: 1 })}><span className="archive-stamp">档案线索 / 1935-01</span><span className="archive-feature-title">一次转折，一种力量。</span><span>从遵义会议，读懂独立自主。<Icon name="arrow" size={17}/></span></button><p className="end-note">循着信仰，慢慢向前。</p>
  </>
}

export function GuidePage({ open, journey, start, arrive, advance, ...robot }: { open: (p: Panel) => void; arrive: () => void; advance: () => void } & VisitProps & RobotProps) {
  const [choice, setChoice] = useState(0)
  const [selected, setSelected] = useState<number | null>(null)
  const [expanded, setExpanded] = useState(false)
  const active = journey?.status === 'active'
  const routeIndex = active ? journey.routeIndex : choice
  const route = routes[routeIndex]
  const target = active ? route.stops[journey.step] : route.stops[0]
  const from = active ? journey.arrived ? target : journey.step > 0 ? route.stops[journey.step - 1] : null : null
  const here = from === null ? [164, 314] : mapPoints[from]
  const walking = walkingInfo(from, target)
  const a = useAudioGuide()
  return <><PageHeader label="馆内导览" title={active ? '下一站，清楚一点。' : '找到你的参观路线'} action={() => open({ kind: 'search' })}/><div className="map-context"><span><Icon name="pin" size={14}/>手动确认位置</span><small>布局与距离为示意</small></div>
    {!active && <div className="segmented" aria-label="路线选择">{routes.map((r, i) => <button key={r.title} aria-pressed={routeIndex === i} onClick={() => setChoice(i)}>{r.minutes} 分钟 · {r.tag.slice(0, 2)}</button>)}</div>}
    <section className={`museum-map action-map ${expanded ? 'expanded' : ''}`} aria-label="行动导览地图"><div className="map-heading"><span>1F <i/> 常设展厅</span><button className="circle-button glass" aria-label={expanded ? '缩小地图' : '展开地图'} onClick={() => setExpanded(!expanded)}><Icon name="expand" size={18}/></button></div><svg viewBox="0 0 354 350" role="img" aria-label={`你在${from === null ? '入口' : exhibits[from].name}，${active && journey.arrived ? '已到达当前展厅' : `前往${exhibits[target].name}`}`}><g className="map-rooms"><path d="M25 35h119v91H25zM202 35h127v91H202zM25 186h87v100H25zM225 186h104v100H225zM135 185h62v80h-62z"/></g><path d="M164 314V299H69V249M69 299H266V247M166 299V221M119 299V151H263V85M119 151H88V85" className="map-route-back"/>{!(active && journey.arrived) && <path d={walkingPath(from, target).map((p, i) => `${i ? 'L' : 'M'}${p[0]} ${p[1]}`).join(' ')} className="direction-path"/>}{exhibits.map((e, i) => <g key={e.id} role="button" tabIndex={0} aria-label={`查看${e.name}`} className={`map-node ${i === target ? 'selected' : ''}`} onClick={() => setSelected(i)} onKeyDown={event => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); setSelected(i) } }}><circle cx={mapPoints[i][0]} cy={mapPoints[i][1]} r="16"/><text x={mapPoints[i][0]} y={mapPoints[i][1] + 4}>0{i + 1}</text></g>)}<g className="map-labels" textAnchor="middle"><text x="88" y="57">遵义会议</text><text x="263" y="57">飞夺泸定桥</text><text x="69" y="208">征途启程</text><text x="266" y="208">雪山草地</text><text x="166" y="196">会师厅</text></g><g className="you-are-here" transform={`translate(${here[0]},${here[1] + (from !== null ? 30 : 0)})`}><circle r="10" fill="white"/><circle r="5" fill="var(--red)"/><text x="0" y="22" textAnchor="middle">你在这里</text></g><g className="map-walk-label"><rect x="126" y="133" width="99" height="32" rx="16"/><text x="176" y="153" textAnchor="middle">{active && journey.arrived ? '已确认到达' : `步行约 ${walking.minutes} 分钟 →`}</text></g></svg><div className="map-legend"><span><i/>当前路线</span><span><i/>其他展厅</span><button onClick={() => setSelected(null)}>回到当前路线<Icon name="pin" size={12}/></button></div></section>
    <section className="navigation-card glass"><div className="navigation-card-top"><span>{active && journey.arrived ? '你已到达' : '接下来去'}</span><span>{active ? `${journey.step + 1} / ${route.stops.length}` : `${route.minutes} 分钟路线`}</span></div><h2>{exhibits[target].name}</h2><p>{active && journey.arrived ? `${exhibits[target].tag} · 建议停留约 ${stopMinutes(routeIndex, journey.step)} 分钟` : `示意距离 ${walking.meters} 米 · 步行约 ${walking.minutes} 分钟`}</p><div className="crowd-note">当前人流：暂无实时数据</div>
      {active ? journey.arrived ? <><Action icon="audio" onClick={() => { a.play(target); open({ kind: 'exhibit', index: target }) }}>听这一站的讲解</Action><Action secondary onClick={advance}>{journey.step === route.stops.length - 1 ? '完成本次参观' : '这一站看完了，去下一站'}</Action></> : <><p className="wayfinding-copy">从{from === null ? '入口' : exhibits[from].name}沿连廊前往{exhibits[target].tag}。请以现场导视为准。</p><Action icon="check" onClick={arrive}>我已到达{exhibits[target].name}</Action></> : <Action icon="compass" onClick={() => start(routeIndex)}>开始这条路线</Action>}
    </section>
    {selected !== null && <div className="selected-exhibit"><span>查看展厅</span><h3>{exhibits[selected].name}</h3><p>{exhibits[selected].tag} · {exhibits[selected].spirit}</p><button onClick={() => open({ kind: 'exhibit', index: selected })}>展厅详情与讲解<Icon name="arrow" size={17}/></button></div>}
    {robot.connected && <CompanionCard {...robot}/>}<SectionTitle title={route.title} more="路线详情" onClick={() => open({ kind: 'route', index: routeIndex })}/><div className="list-group">{route.stops.map((i, n) => <button className="list-row" key={i} onClick={() => open({ kind: 'exhibit', index: i })}><span className={`list-number ${active && n < journey.step ? 'stop-done' : ''}`}>{active && n < journey.step ? <Icon name="check" size={14}/> : `0${n + 1}`}</span><span className="row-text"><strong>{exhibits[i].name}</strong><small>{exhibits[i].tag} · 建议 {stopMinutes(routeIndex, n)} 分钟</small></span>{active && n === journey.step ? <span className="current-tag">当前站</span> : <Icon name="chevron" size={14}/>}</button>)}</div></>
}

export function CinemaPage({ open, projection }: { open: (p: Panel) => void; projection: Projection }) {
  const [category, setCategory] = useState('全部')
  return <><PageHeader label="空间里的故事" title="沉浸放映" action={() => open({ kind: 'search' })}/><p className="page-description">手机是控制器，空间才是屏幕。</p><section className="projection-room"><div><Icon name="cinema" size={26}/><span><strong>投影厅 A</strong><small>{projection.filmIndex === null ? '空闲 · 可以发起放映' : `${projection.playing ? '正在放映' : '已暂停'} · ${films[projection.filmIndex].title}`}</small></span><span className="demo-chip">演示</span></div><button onClick={() => open({ kind: 'movie', index: projection.filmIndex ?? 1 })}>{projection.filmIndex === null ? '选择雪山草地故事' : '返回放映控制'}<Icon name="arrow" size={17}/></button></section><div className="text-tabs" aria-label="影片分类">{['全部', '历史纪事', '长征故事', '人物叙事'].map(c => <button aria-pressed={category === c} onClick={() => setCategory(c)} key={c}>{c}</button>)}</div>
    {films.map((film, i) => (category === '全部' || category === film.category) && <button className={`film-card ${i === 1 ? 'featured' : ''}`} key={film.id} onClick={() => open({ kind: 'movie', index: i })}><div className="film-picture"><FilmArtwork motif={film.motif}/><span className="film-year">{film.year}<small>长征影像计划</small></span><span className="film-duration glass"><Icon name="play" size={12}/>{formatTime(film.duration)}</span></div><div className="film-description"><div><small>{film.category} · 策划内容</small><h2>{film.title}</h2><p>{film.label}</p></div><span className="round-arrow"><Icon name="arrow" size={20}/></span></div></button>)}<p className="end-note">当前体验放映控制流程，授权影片与真实设备待接入。</p></>
}

export function ExplorePage({ open, completed, journey }: { open: (p: Panel) => void; completed: string[]; journey: Journey | null }) {
  const current = journey?.status === 'active' ? routes[journey.routeIndex].stops[journey.step] : 2
  return <><PageHeader label="在展厅里发现" title="抬起头，找一找。" action={() => open({ kind: 'settings' })} icon="settings"/><p className="page-description">先观察一件展陈，再带回你的发现。</p><button className="observation-feature" onClick={() => open({ kind: 'observation', index: current })}><span className="archive-stamp">{exhibits[current].tag} · 约 2 分钟</span><Icon name="explore" size={37}/><h2>{evidence[current].observation}</h2><span>去观察<Icon name="arrow" size={22}/></span></button><p className="context-note">任务中的展陈为策划线索。现场如无对应展品，可查看资料，不会记作现场完成。</p><SectionTitle title="沿途的观察任务"/><div className="list-group">{exhibits.map((e, i) => <button className="list-row" key={e.id} onClick={() => open({ kind: 'observation', index: i })}><span className="list-number">0{i + 1}</span><span className="row-text"><strong>{e.name}</strong><small>{completed.includes(`observe-${e.id}`) ? '观察已完成' : evidence[i].objects[0]}</small></span><Icon name={completed.includes(`observe-${e.id}`) ? 'check' : 'chevron'} size={16}/></button>)}</div><SectionTitle title="参观之后，再想一想"/><div className="list-group"><button className="list-row" onClick={() => open({ kind: 'game', index: 0 })}><Icon name="route"/><span className="row-text"><strong>串联长征路线</strong><small>回顾重要节点</small></span><Icon name="chevron" size={14}/></button><button className="list-row" onClick={() => open({ kind: 'game', index: 1 })}><Icon name="book"/><span className="row-text"><strong>长征五问</strong><small>离馆后的知识回顾</small></span><Icon name="chevron" size={14}/></button></div><p className="end-note">把更多时间，留给眼前的展览。</p></>
}

export function ProfilePage({ open, saved, journey }: { open: (p: Panel) => void; saved: Saved; journey: Journey | null }) {
  return <><PageHeader label="我的参观足迹" title="每一步，都算数" action={() => open({ kind: 'settings' })} icon="settings"/><div className="profile-person"><span className="profile-monogram"><BrandMark size={40}/></span><div><h2>同行的你</h2><p>陪你走完一段历史。</p></div></div><div className="profile-stats"><div><strong>{saved.visited.length}<small> / 5</small></strong><span>走近的展厅</span></div><div><strong>{saved.completed.filter(c => c.startsWith('observe-')).length}<small> / 5</small></strong><span>观察印记</span></div><div><strong>{saved.favorites.length}</strong><span>珍藏内容</span></div></div><section className="footprint-card"><span className="eyebrow">{journey ? routes[journey.routeIndex].title : '属于你的征途'}</span><h2>{journey?.status === 'finished' ? '这一程，已完成。' : '循着信仰，慢慢向前。'}</h2><JourneyArtwork progress={{ step: journey?.step ?? -1, total: journey ? routes[journey.routeIndex].stops.length : 5, finished: journey?.status === 'finished' }}/><div className="footprint-stops">{exhibits.map((e, i) => <button aria-label={`查看${e.name}`} className={saved.visited.includes(e.id) ? 'done' : ''} key={e.id} onClick={() => open({ kind: 'exhibit', index: i })}><i>{saved.visited.includes(e.id) ? <Icon name="check" size={12}/> : i + 1}</i><span>{['出发', '遵义', '泸定', '雪山', '会师'][i]}</span></button>)}</div></section><div className="list-group profile-links"><button className="list-row" onClick={() => open({ kind: 'collection' })}><Icon name="heart"/><span className="row-text"><strong>我的收藏</strong></span><span className="muted">{saved.favorites.length}</span><Icon name="chevron" size={14}/></button><button className="list-row" onClick={() => open({ kind: 'card' })}><Icon name="download"/><span className="row-text"><strong>旅程纪念卡</strong></span><Icon name="chevron" size={14}/></button><button className="list-row" onClick={() => open({ kind: 'settings' })}><Icon name="settings"/><span className="row-text"><strong>阅读与显示</strong></span><Icon name="chevron" size={14}/></button></div><p className="end-note">足迹保存在当前设备，无需登录。</p></>
}
